Added passphrase handling
Keeper-Security/git-ssh-sign pull request #40
Opened 2024-01-11 01:03 UTC by idimov-keeper

2024-01-11 14:09 UTC, EndlessTrax requested changes

2024-01-11 14:09 UTC, EndlessTrax commented on internal/vault/vault.go
> +	pass := records[0].GetFieldsByType("password")[0]["value"].([]interface{})[0].(string)
If no passphrase is set in the record, this line fails and returns the below error to the user. Please add error handling for this use case.

```
error: panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/Keeper-Security/git-ssh-sign/internal/vault.FetchKeys({0xc000016210, 0x16})
        C:/Users/RickyWhite/Code/Keeper/git-ssh-sign/internal/vault/vault.go:74 +0x4ef
main.main()
        C:/Users/RickyWhite/Code/Keeper/git-ssh-sign/cmd/ssh-sign/main.go:74 +0x4e5

fatal: failed to write commit object
```

2024-01-12 15:08 UTC, EndlessTrax approved these changes

2024-01-12 15:10 UTC, EndlessTrax approved these changes

2024-01-16 15:37 UTC, amigus approved these changes

2024-01-16 15:45 UTC, merged